import SEO from '../components/SEO';

export default function TermsOfUse() {
    return (
        <div className="bg-[#040406] min-h-screen relative overflow-x-hidden font-product-sans text-white">
            <SEO
                title="Terms & Conditions"
                description="Read FastTV's Terms and Conditions. Understand our policies for using the FastTV platform, user accounts, content rights, and more."
                keywords="FastTV terms, terms and conditions, user agreement, content policy, legal"
                canonicalPath="/terms"
            />
            {/* Background */}
            <div className="absolute top-0 left-0 right-0 h-[100vh] pointer-events-none">
                <div className="absolute inset-0 bg-gradient-to-t from-[#040406] via-[#040406]/60 to-transparent" />
            </div>

            <div className="relative z-10 pt-10 md:pt-[120px] pb-20 container mx-auto px-6">
                <div className="hidden md:block">
                    <h1 className="text-[40px] md:text-[56px] font-bold mb-4 text-center uppercase tracking-wider">Terms &amp; Conditions</h1>
                    <p className="text-center text-white/50 text-sm italic mb-12">Effective Date: March 1, 2026 &middot; Last Updated: March 1, 2026</p>
                </div>

                <div className="max-w-4xl mx-auto space-y-12 text-white/80 leading-relaxed font-light">

                    {/* Clause 1 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">1. Electronic Record and Parties</h2>
                        <p className="mb-4">
                            These Terms and Conditions (&ldquo;Terms&rdquo;) constitute an electronic record within the meaning of the Information Technology Act, 2000 (&ldquo;IT Act&rdquo;) and rules made thereunder, as amended from time to time, and other applicable statutes governing electronic records in India. This electronic record is generated by a computer system and does not require any physical or electronic signature thereunder.
                        </p>
                        <p>
                            These Terms constitute a legally binding agreement between you (&ldquo;User&rdquo;, &ldquo;you&rdquo;, or &ldquo;your&rdquo;) and Hungama Digital Media Entertainment Private Limited, a company incorporated under the Companies Act, 2013, having its registered office at C-Wing, 10th Floor, Times Square Building, Andheri Kurla Road, Marol, Andheri (E), Mumbai 400059, Maharashtra, India (for Users accessing the Services from India); hereinafter collectively referred to as &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;.
                        </p>
                    </section>

                    {/* Clause 2 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">2. Scope of Services</h2>
                        <p>
                            These Terms govern your access to and use of (i) the mobile applications available on Android and iOS platforms (the &ldquo;Apps&rdquo;); and (ii) all related services, features, functionalities, and content offered through the Site and Apps (collectively, the &ldquo;Services&rdquo;), including without limitation short-form micro-drama audio-visual entertainment content, subscription plans for users in India, subscription plans plus coin-based pay-per-show access for international users, content sharing capabilities, push notifications and related features.
                        </p>
                    </section>

                    {/* Clause 3 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">3. Acceptance of Terms</h2>
                        <p className="mb-4">
                            By downloading, installing, registering an account with, accessing, browsing, or otherwise using the Services in any manner, you acknowledge that you/your parent/legal guardian (in case of minors) consent, agree and undertake to have read, understood, and expressly agree to be bound by these Terms, our Privacy Policy, our Community Guidelines, the Coins Terms and Conditions (where applicable), and all other policies, guidelines, and additional terms incorporated herein by reference.
                        </p>
                        <p className="mb-4">
                            Unless otherwise specified, the Services are available for individuals who have attained the age of majority, i.e., 18 years and above in the case of India. If you are below the relevant age of majority in your jurisdiction, you may access the Services/app only under the supervision of a parent/guardian and in accordance with applicable law. However, in all cases, only persons of the age of majority are allowed to register an Account on the Services and will always be responsible for the operation of any such Account.
                        </p>
                        <p>
                            If you do not agree to these Terms or any referenced policies, you must immediately cease all access to and use of the Services.
                        </p>
                    </section>

                    {/* Clause 4 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">4. Geographic Scope and Compliance</h2>
                        <p>
                            For Users in India, the Services are controlled and made available from servers and facilities located in India. For Users outside India, access to and use of the Services is provided subject to compliance with local laws and licensing restrictions. Content availability, features, monetization models, and permitted uses may vary by territory due to licensing agreements, regulatory requirements, and technical limitations. You are solely responsible for ensuring that your use of the Services complies with all applicable laws in your jurisdiction.
                        </p>
                    </section>

                    {/* Clause 5 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">5. Eligibility Requirements</h2>
                        <p className="mb-4">
                            You must be at least eighteen (18) years of age and have reached the age of majority under the laws of your jurisdiction of residence to access, register for, or use the Services. By using the Services, you represent and warrant that you meet these age requirements and have the full legal capacity to enter into these Terms.
                        </p>
                        <p className="mb-4">
                            You represent and warrant that you are legally competent to form a binding contract under applicable law and are not barred from using the Services under any applicable law, regulation, or order.
                        </p>
                        <p>
                            A parent/legal guardian may create and manage an Account for a minor in accordance with these Terms and applicable law. Accounts and licenses are otherwise not transferable.
                        </p>
                    </section>

                    {/* Clause 6 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">6. Account Registration and Security</h2>
                        <p className="mb-4">
                            Registration and creation of a user account (&ldquo;Account&rdquo;) is mandatory to access the Services. To create an Account, you must provide complete, accurate, and current information including, without limitation, your full name, email address, mobile phone number, date of birth, and country of residence (&ldquo;Registration Information&rdquo;).
                        </p>
                        <p className="mb-4">
                            In addition to direct registration, you may register using supported third-party social login services, subject to their respective terms and privacy policies.
                        </p>
                        <p className="mb-4">
                            You agree to keep your Registration Information accurate, complete, and up-to-date at all times; maintain the confidentiality and security of your Account credentials (username, password, and any security questions); notify us immediately of any unauthorized access or use of your Account; and be fully responsible and liable for all activities that occur under your Account.
                        </p>
                        <p className="mb-4">
                            You shall not create an Account using false, inaccurate, or misleading information; create fake profiles or impersonate any person or entity; create Accounts for anyone other than yourself without their express authorization; use another person&rsquo;s name, likeness, or credentials without permission; or create multiple Accounts for fraudulent purposes or to circumvent suspensions/terminations.
                        </p>
                        <p className="mb-4">
                            We reserve the right to verify your identity and Registration Information at any time; refuse registration of any username or Account in our sole discretion; suspend, restrict, or terminate your Account for any violation of these Terms, suspicious activity, non-payment, or legal requirement.
                        </p>
                        <p className="mb-4">
                            You may terminate your Account at any time by contacting support. Upon termination, you will retain access through the end of any paid subscription period (if applicable), after which all access ceases.
                        </p>
                        <p>
                            Upon termination or suspension of your Account: your right to access the Services immediately ceases; all prepaid subscriptions, coins, or credits may be forfeited subject to applicable refund policy; we may retain your Registration Information as required by law; and these Terms shall continue to apply to your prior use of the Services.
                        </p>
                    </section>

                    {/* Clause 7 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">7. Privacy Policy</h2>
                        <p className="mb-4">
                            Our Privacy Policy, as amended from time to time, is expressly incorporated into and forms part of these Terms. The Privacy Policy explains our practices regarding the collection, use, storage, disclosure, transfer, and protection of personal information and other data obtained through your use of the Services.
                        </p>
                        <p className="mb-4">
                            To provide the Services, facilitate account management, enable payments, deliver personalized content recommendations, and conduct analytics, we collect personal information including full name, email address, mobile phone number, date of birth, country of residence, and device identifiers; approximate location (derived from IP address and device settings), device type, operating system, app version, and interaction patterns; billing information processed through third-party payment gateways; and usage analytics.
                        </p>
                        <p>
                            The Apps do not request, access, or collect: (a) Camera or photo library permissions; (b) Microphone permissions; (c) Contacts or address book access; or (d) Precise geolocation data.
                        </p>
                    </section>

                    {/* Clause 8 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">8. Data Retention and Deletion</h2>
                        <p className="mb-4">
                            We retain user data in accordance with our Privacy Policy and applicable laws, aligned with industry standards for OTT platforms. Registration Information shall be retained for such period following Account deletion, cancellation, or withdrawal, or such longer period as required by applicable law; transaction and payment records are retained for the duration required by applicable financial regulations; and usage analytics data is retained as necessary for service improvement and legal compliance.
                        </p>
                        <p>
                            You may request deletion of your personal data by contacting us. We will process such requests in accordance with applicable laws.
                        </p>
                    </section>

                    {/* Clause 9 */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">9. Third-Party Data Processors</h2>
                        <p className="mb-4">
                            We use third-party services for legitimate business purposes and your use of third-party services is governed by their respective privacy policies and terms of service. We encourage you to review these policies before connecting your accounts. We are not responsible for the practices, content, or data handling of third parties.
                        </p>
                        <p className="mb-4">
                            Personal information may be transferred to, stored, and processed in India and other jurisdictions where our service providers operate. For international Users, such transfers are subject to appropriate safeguards as required by applicable data protection laws.
                        </p>
                        <p>
                            Users located in India and other jurisdictions with data protection may have rights to access, rectify, erase, restrict processing, data portability, and object to processing of their personal data. To exercise these rights, contact us. We will respond within the timelines mandated by applicable law.
                        </p>
                    </section>

                    {/* Clauses 11-15: License Grant and Content Usage */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">10. License Grant and Content Usage</h2>
                        <p className="mb-4">
                            The Services provide access to short-form micro-drama audio-visual entertainment content (&ldquo;Content&rdquo;), including episodic stories, serials, and related multimedia materials owned or licensed by Hungama or its content partners. Content is delivered through streaming and limited offline download capabilities where available. Content availability is subject to: (a) licensing agreements; (b) geographic restrictions; (c) technical compatibility; and (d) our sole discretion. We do not guarantee that any specific Content will be available at any particular time or location.
                        </p>
                        <p className="mb-4">
                            Subject to your compliance with these Terms, payment of applicable fees (where required), and during the term of your active Account, we grant you a limited, worldwide, non-exclusive, non-transferable, non-sublicensable, revocable, personal license to: (a) access, view, and listen to Content solely through the Site and Apps for your personal, non-commercial entertainment purposes; (b) use content sharing features to share links to Content with others via supported platforms subject to sharing limitations.
                        </p>
                        <p className="mb-4">
                            You may not, nor permit any third party to: (a) copy, reproduce, distribute, publicly display, publicly perform, transmit, broadcast, or make Content available except as expressly authorized; (b) modify, adapt, translate, create derivative works from, or alter Content in any manner; (c) reverse engineer, decompile, disassemble, or attempt to derive source code from the Services or Content; (d) remove, obscure, or alter any copyright, trademark, or proprietary rights notices contained in Content; (e) use Content for commercial purposes, including advertising, sponsorships, or monetization; (f) rent, lease, lend, sell, or redistribute Content; (g) use automated systems, bots, scrapers, or similar technologies to access or extract Content; or (h) circumvent, disable, or interfere with digital rights management, geographic restrictions, or technical protection measures.
                        </p>
                        <p className="mb-4">
                            You may use in-App sharing features to generate links to Content for personal sharing via social media, messaging apps, or email. Shared links: (a) direct recipients to the Services where access requires valid subscription or coin purchase; (b) do not grant direct Content access; and (c) are subject to daily or periodic limits to prevent abuse. You may not share Account credentials or enable unauthorized third-party access to Content.
                        </p>
                        <p>
                            Content access is subject to licensing territory restrictions. You agree not to use VPNs, proxies, location spoofing, or similar technologies to circumvent geographic limitations. We may suspend access detected as violating geo-restrictions. Content quality and availability vary by device, operating system, internet bandwidth, and location. You are responsible for maintaining compatible devices and internet connections.
                        </p>
                    </section>

                    {/* Clause 5: Content Ownership and Intellectual Property */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">11. Content Ownership and Intellectual Property Rights</h2>
                        <p className="mb-4">
                            Hungama, together with its licensors, content partners, and affiliates, is the sole and exclusive owner of all rights, title, and interest in and to the Services and all Content, including without limitation all copyrights, trademarks, patents, trade secrets, moral rights, database rights, and other intellectual property rights or proprietary rights therein throughout the world. Except for the limited license expressly granted above, no right, title, or interest in or to the Services or Content is transferred to you.
                        </p>
                        <p className="mb-4">
                            All intellectual property rights in the Site, Apps, software, algorithms, user interfaces, design elements, branding, logos, and technical infrastructure powering the Services (&ldquo;Platform IP&rdquo;) are exclusively owned by Hungama. You may not use, copy, modify, adapt, translate, reverse engineer, decompile, disassemble, or create derivative works from any Platform IP except as expressly permitted herein.
                        </p>
                        <p className="mb-4">
                            All Content contains copyright, trademark, and proprietary rights notices. You agree to abide by and maintain all such notices, legends, and attributions. You shall not remove, obscure, alter, or circumvent any copyright management information, digital rights management systems, watermarks, or technical protection measures embedded in or applied to Content or the Services.
                        </p>
                        <p className="mb-4">
                            The Services do not currently permit user-generated content uploads, comments, ratings, or similar user contributions. All Content is either owned by Hungama or licensed from third-party content providers under separate agreements.
                        </p>
                        <p className="mb-4">
                            Hungama self-classifies content into U, U/A 7+, U/A 13+, U/A 16+, and A (18+) along with descriptive tags, which are displayed on Fasttv.app. You should exercise your full discretion in viewing the Content.
                        </p>
                        <p className="mb-4">
                            If you believe your copyright-protected work has been made available on the Services without authorization, please submit a takedown notice containing: your contact information (email, physical address, phone number); identification of the copyrighted work claimed to be infringed; identification of the allegedly infringing material including URLs or specific descriptions; a statement that you have good faith belief the use is not authorized by the copyright owner, its agent, or law; a statement under penalty of perjury that the information is accurate and you are the copyright owner or authorized to act on their behalf.
                        </p>
                        <p>
                            We will process valid notices in accordance with applicable laws including the IT Act and respond within timelines mandated thereunder. Counter-notices may be submitted by affected users. All rights not expressly granted herein are expressly reserved by Hungama and its licensors.
                        </p>
                    </section>

                    {/* Clause 6: Monetization, Subscriptions and Payments */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">12. Monetization, Subscriptions and Payments</h2>
                        <p className="mb-4">
                            The Services operate on a model where full access to premium Content operates on a subscription model for Users located in India and a subscription + virtual coin-based model for Users located outside India.
                        </p>
                        <p className="mb-4">
                            Users in India and optionally international users may purchase subscription plans that provide time-bound access to all premium Content for the duration of the selected billing period. By purchasing a subscription, you authorize Hungama and its third-party payment processors to charge the applicable subscription fee to your selected payment method on a recurring basis until you cancel.
                        </p>
                        <p className="mb-4">
                            Users accessing the Services from outside India may additionally access premium Content by purchasing virtual coins (&ldquo;Coins&rdquo;) through in-app purchases. Coins are a virtual, non-monetary digital currency that may be used solely within the Services to unlock specific episodes or Content on a pay-per-show basis. Coins have no cash value, are non-refundable, non-transferable, and cannot be redeemed for money or used outside the Services.
                        </p>
                        <p className="mb-4">
                            All payments are processed by third-party payment service providers. You represent and warrant that you are the lawful owner or authorized user of the payment method you provide. You are responsible for ensuring that all payment information is accurate and up to date and for paying all applicable fees, charges, and taxes.
                        </p>
                        <p className="mb-4">
                            All paid subscriptions renew automatically at the end of each billing period at the then-current subscription price, unless you cancel before the renewal date. You can cancel your subscription at any time via the account or subscription settings within the App.
                        </p>
                        <p className="mb-4">
                            From time to time, we may offer free trial periods for certain subscription plans. A free trial plan shall be applicable to first-time users, one user once in a lifetime. Unless you cancel before the end of the free trial period, your subscription will automatically convert to a paid subscription.
                        </p>
                        <p className="mb-4">
                            If you cancel a paid subscription, you will continue to have access to the subscription benefits until the end of the then-current billing period, after which your access to premium Content will cease.
                        </p>
                        <p className="mb-4">
                            Refunds are strictly limited. Users may be eligible for a refund of subscription fees if they submit a refund request. Any approved refund will be processed to the original payment method within approximately five to seven (5–7) business days. Purchases of Coins, Promotional Coins, in-app purchases, and subscription fees in respect of which premium Content has been accessed are non-refundable.
                        </p>
                        <p className="mb-4">
                            We reserve the right to change subscription prices, introduce new plans, modify the pricing of Coins, or alter plan features at any time. Such changes will be effective from the start of your next billing period after notice is provided.
                        </p>
                        <p className="mb-4">
                            All prices and fees displayed are inclusive of any applicable taxes, unless expressly stated otherwise. You are solely responsible for paying all applicable taxes and charges.
                        </p>
                        <p className="mb-4">
                            If any payment is declined or cannot be collected, we may suspend or restrict your access to premium Content until full payment is received. Repeated payment failures may result in termination of your account.
                        </p>
                        <p>
                            Subscription prices for India are displayed in Indian Rupees (INR). Prices for international Users are displayed in the local currency supported by the relevant app store or payment provider.
                        </p>
                    </section>

                    {/* Clause 7: User Conduct and Prohibited Activities */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">13. User Conduct and Prohibited Activities</h2>
                        <p className="mb-4">
                            You agree to use the Services only in compliance with all applicable laws, rules, regulations, ordinances, and other legal requirements of the jurisdiction(s) in which you access and use the Services.
                        </p>
                        <p className="mb-4">
                            As a condition of your use, you expressly agree that you will not, and will not attempt to, permit any third party to: (a) access or use the Services for any unlawful purpose; (b) copy, reproduce, modify, adapt, distribute, or exploit any Content except as expressly permitted; (c) circumvent, disable, or interfere with security-related features, DRM, or geographic restrictions; (d) access the Services using automated means (bots, scrapers, etc.); (e) transmit viruses, malware, or other harmful code; (f) share Account credentials with third parties; (g) impersonate any person or entity; (h) interfere with or disrupt the Services&rsquo; infrastructure; (i) engage in unauthorized commercial activities; (j) collect personal data about other users without consent; (k) use the Services for obscene, defamatory, or otherwise unlawful purposes; (l) violate third-party intellectual property or privacy rights; or (m) encourage others to do any of the foregoing.
                        </p>
                        <p className="mb-4">
                            Accounts are intended for individual personal use only. Simultaneous access across multiple devices may be limited based on your subscription plan.
                        </p>
                        <p className="mb-4">
                            We reserve the right to monitor usage for compliance and upon detection of any violation: (a) suspend or terminate your Account without notice; (b) forfeit any prepaid fees, Coins, or credits; (c) remove offending content or activities; and (d) take appropriate legal action.
                        </p>
                        <p>
                            If you encounter Content or activity that you believe violates these Terms or applicable law, please report it through the in-App reporting mechanism or by contacting support.
                        </p>
                    </section>

                    {/* Clause 8: Third-Party Services and Advertisements */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">14. Third-Party Services and Advertisements</h2>
                        <p className="mb-4">
                            The Services may contain links to, integrations with, or functionality that connects to third-party websites, services, applications, content, payment processors, app stores, social media platforms, and other resources (collectively, &ldquo;Third-Party Services&rdquo;). Hungama does not own, control, monitor, endorse, or assume any responsibility for Third-Party Services.
                        </p>
                        <p className="mb-4">
                            Your use of any Third-Party Services is solely between you and the relevant third-party provider at your own risk and is governed entirely by the third party&rsquo;s terms of service and privacy policy. Hungama expressly disclaims all liability arising from your use of Third-Party Services.
                        </p>
                        <p className="mb-4">
                            The Services may display advertisements, sponsored content, promotions, or branded materials. We reserve the right to place advertising within or in connection with the Services or Content at our discretion.
                        </p>
                        <p className="mb-4">
                            The inclusion of links, integrations, or advertisements does not imply endorsement, recommendation, warranty, or verification by Hungama.
                        </p>
                        <p className="mb-4">
                            To the maximum extent permitted by law, Hungama shall not be liable for: (a) any loss, damage, or harm arising from your use of Third-Party Services; (b) the content or availability of Third-Party Services; (c) any transactions conducted through Third-Party Services; or (d) the privacy or security practices of third parties.
                        </p>
                        <p>
                            We reserve the right to modify, suspend, or discontinue any Third-Party Services integrations at any time without notice or liability.
                        </p>
                    </section>

                    {/* Clause 9: Service Availability and Technical Requirements */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">15. Service Availability and Technical Requirements</h2>
                        <p className="mb-4">
                            The Services, Apps, and Content are provided strictly on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. Hungama makes no warranties of any kind regarding uninterrupted availability, error-free operation, security, or performance of the Services.
                        </p>
                        <p className="mb-4">
                            The Services may be temporarily unavailable due to scheduled or unscheduled maintenance, system upgrades, technical failures, internet outages, third-party service disruptions, force majeure events, or other causes beyond our reasonable control.
                        </p>
                        <p className="mb-4">
                            You are solely responsible for obtaining and maintaining: (a) all hardware, software, equipment, and internet access necessary to use the Services; (b) compatible devices (current Android/iOS versions) and operating systems; (c) sufficient bandwidth and data connectivity; and (d) payment for all communication charges incurred.
                        </p>
                        <p className="mb-4">
                            The Apps may automatically download and install updates, patches, bug fixes, enhancements, or new versions. You agree not to block, disable, or interfere with automatic updates.
                        </p>
                        <p className="mb-4">
                            Content availability, quality, and functionality may vary by geographic location, device type, operating system, internet connection speed, and bandwidth. Some features or Content may not be available in all territories or on all devices.
                        </p>
                        <p>
                            You agree to comply with all applicable export control laws and regulations. The Services and Content may not be downloaded, exported, or re-exported to any sanctioned or embargoed country or territory.
                        </p>
                    </section>

                    {/* Clause 10: Termination and Suspension */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">16. Termination and Suspension</h2>
                        <p className="mb-4">
                            You may terminate your Account at any time by contacting support or deleting your Account through the App settings. Upon termination: (a) you will retain access to premium Content through the end of any prepaid subscription; (b) all Coins, promotional credits, and unused entitlements will be forfeited and non-refundable; (c) your right to use the Services immediately ceases thereafter; and (d) these Terms continue to apply to your prior use.
                        </p>
                        <p className="mb-4">
                            Hungama reserves the right to suspend, restrict, or terminate your Account at any time and without prior notice for: (a) violation of these Terms; (b) non-payment or payment failures; (c) suspicious, fraudulent, or illegal activity; (d) abuse or excessive usage patterns; (e) legal or governmental requirements; (f) prolonged inactivity; or (g) any conduct impairing the security or integrity of the Services.
                        </p>
                        <p className="mb-4">
                            The following provisions survive termination: (a) intellectual property ownership clauses; (b) disclaimers and limitation of liability; (c) indemnity obligations; (d) payment obligations; (e) dispute resolution and governing law; and (f) any other provision that by its nature should survive.
                        </p>
                        <p>
                            Terminated Accounts cannot be recovered. Suspended Accounts may be restored at our sole discretion upon resolution of the underlying issue.
                        </p>
                    </section>

                    {/* Clause 11: Disclaimers and Limitation of Liability */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">17. Disclaimers and Limitation of Liability</h2>
                        <p className="mb-4">
                            To the maximum extent permitted by applicable law, the Services are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind. Hungama disclaims all warranties including: (a) warranties of merchantability, fitness for a particular purpose, title, and non-infringement; (b) warranties of uninterrupted access, error-free operation, security, or compatibility; (c) warranties arising from course of dealing; and (d) any warranties regarding the accuracy of Content or Third-Party Services.
                        </p>
                        <p className="mb-4">
                            To the fullest extent permitted by law, Hungama, its affiliates, licensors, service providers, officers, directors, employees, and agents (collectively, &ldquo;Company Parties&rdquo;) shall not be liable for any direct, indirect, incidental, special, punitive, exemplary, or consequential damages, including loss of profits, revenues, goodwill, data, use, or anticipated savings.
                        </p>
                        <p className="mb-4">
                            Our aggregate liability for any and all claims arising out of or relating to the Services shall not exceed the amount actually paid by you for accessing the specific item of content giving rise to the claim. This limitation survives termination.
                        </p>
                        <p className="mb-4">
                            You expressly acknowledge that use of the Services involves inherent risks, including data loss, service interruptions, exposure to objectionable content, and interactions with Third-Party Services. You assume all risk associated with your use of the Services.
                        </p>
                        <p>
                            Some jurisdictions do not allow exclusion of implied warranties or limitation of liability for incidental/consequential damages, so the above limitations may not fully apply to you.
                        </p>
                    </section>

                    {/* Clause 12: Indemnification */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">18. Indemnification</h2>
                        <p className="mb-4">
                            You agree to defend, indemnify, and hold harmless Hungama, its affiliates, licensors, service providers, officers, directors, employees, agents, successors, and assigns (&ldquo;Indemnified Parties&rdquo;) from and against any and all claims, damages, losses, liabilities, and expenses arising out of or relating to: (a) your access to or use of the Services; (b) your violation of these Terms; (c) your violation of any applicable law or third-party rights; (d) your payment information or transactions; (e) your communications or interactions through the Services; or (f) any claims arising from your negligence, willful misconduct, or fraudulent activity.
                        </p>
                        <p>
                            The Indemnified Parties reserve the right to assume exclusive defense and control of any matter subject to indemnification, in which event you agree to cooperate fully. You may not settle any claim without prior written consent from Hungama.
                        </p>
                    </section>

                    {/* Clause 13: Copyright Infringement and Takedown Notices */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">19. Copyright Infringement and Takedown Notices</h2>
                        <p className="mb-4">
                            Hungama respects intellectual property rights. We have implemented procedures compliant with the Digital Millennium Copyright Act (DMCA) for U.S. Users and the Information Technology Act, 2000 for India Users.
                        </p>
                        <p className="mb-4">
                            If you believe your copyrighted work has been made available without authorization, submit a notice to our designated Grievance Officer at <a href="mailto:grievance@fasttv.app" className="text-[#009cdb] hover:underline">grievance@fasttv.app</a> containing: (a) your contact information; (b) identification of the copyrighted work; (c) identification of the infringing material (URLs or precise location); (d) a statement of good faith; (e) a statement under penalty of perjury; (f) for India Users: undertaking to file infringement suit within 21 days; (g) your signature.
                        </p>
                        <p>
                            We will process valid notices promptly and take appropriate action in accordance with applicable law. Counter-notices may be submitted by users.
                        </p>
                    </section>

                    {/* Clause 14: Grievance Redressal */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">20. Grievance Redressal Mechanism</h2>
                        <p className="mb-4">
                            In compliance with Rule 11 of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, Hungama has appointed a Grievance Officer:
                        </p>
                        <div className="bg-white/5 border border-white/10 rounded-xl p-6 mb-4">
                            <p><strong className="text-white">Name:</strong> Rachna Shroff</p>
                            <p><strong className="text-white">Designation:</strong> Grievance Officer</p>
                            <p><strong className="text-white">Email:</strong> <a href="mailto:grievance@fasttv.app" className="text-[#009cdb] hover:underline">grievance@fasttv.app</a></p>
                            <p><strong className="text-white">Address:</strong> C-Wing, 10th Floor, Times Square Building, Andheri Kurla Road, Marol, Andheri (E), Mumbai 400059, Maharashtra</p>
                        </div>
                        <p className="mb-4">
                            Submit grievances via email including: (a) complainant name and contact details; (b) detailed description of grievance; (c) date/time of issue (if applicable); (d) URL/title of specific Content; and (e) supporting evidence.
                        </p>
                        <p>
                            We acknowledge receipt within 24 hours and resolve/escalate within 15 days (or sooner if required by law). Unique ticket numbers are issued for tracking.
                        </p>
                    </section>

                    {/* Clause 15: Communications and Notifications */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">21. Communications and Notifications</h2>
                        <p className="mb-4">
                            By accepting these Terms, you expressly consent to receive communications from Hungama via email, SMS, push notifications, in-App messages, or other electronic means, including: (a) transactional notices; (b) service communications; (c) promotional content; and (d) authentication/verification messages.
                        </p>
                        <p className="mb-4">
                            Limited opt-out is available for promotional communications via App settings. Transactional/service communications cannot be opted out.
                        </p>
                        <p>
                            We are not responsible for failed delivery due to incorrect contact information, spam filters, or carrier issues. Updating contact details is your responsibility.
                        </p>
                    </section>

                    {/* Clause 16: Governing Law and Jurisdiction */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">22. Governing Law and Jurisdiction</h2>
                        <p className="mb-4">
                            These Terms shall be governed by and construed in accordance with the laws of India without regard to conflict of law principles.
                        </p>
                        <p className="mb-4">
                            All disputes arising out of or relating to these Terms or the Services shall be subject to the exclusive jurisdiction of courts located in Mumbai, Maharashtra, India. For Users outside India, disputes shall be resolved exclusively by binding arbitration administered by the Singapore International Arbitration Centre (&ldquo;SIAC&rdquo;) under SIAC Rules. Arbitration seat: Singapore; language: English.
                        </p>
                        <p>
                            Notwithstanding the above, either party may seek injunctive relief in competent court for IP infringement or unauthorized Services use.
                        </p>
                    </section>

                    {/* Clause 17: Miscellaneous */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">23. Miscellaneous Provisions</h2>
                        <p className="mb-4">
                            These Terms, together with the Privacy Policy, Coins Terms, and other incorporated documents, constitute the entire agreement between you and Hungama regarding the Services, superseding prior agreements. If any provision is held invalid/unenforceable, remaining provisions continue in full force. Invalid provisions are reformed to maximum enforceable extent. Failure to enforce any right does not constitute waiver. Waivers are effective only in writing signed by authorized representative.
                        </p>
                        <p>
                            You may not assign these Terms without consent. Hungama may assign freely to affiliates, successors, or in merger/acquisition. These Terms and all notices are electronic. You consent to electronic records/signatures with same legal effect as written.
                        </p>
                    </section>

                    {/* Clause 19: Changes to Terms */}
                    <section>
                        <h2 className="text-[24px] font-bold text-white mb-4">24. Changes to Terms</h2>
                        <p className="mb-4">
                            Hungama reserves the right to modify these Terms at any time. Material changes will be posted on the Site/Apps with an effective date. Minor changes are effective immediately.
                        </p>
                        <p className="mb-4">
                            Changes are notified via email, push notification, or prominent Site/App notice. Continued use after changes constitutes acceptance. Check Terms periodically. Continued use binds you to revised Terms.
                        </p>
                        <p>
                            For questions, contact us at:<br />
                            Email: <a href="mailto:grievance@fasttv.app" className="text-[#009cdb] hover:underline">grievance@fasttv.app</a><br />
                            Privacy: <a href="mailto:privacy@fasttv.app" className="text-[#009cdb] hover:underline">privacy@fasttv.app</a><br />
                            Website: <a href="https://fasttv.app/" target="_blank" rel="noopener noreferrer" className="text-[#009cdb] hover:underline">https://fasttv.app/</a>
                        </p>
                    </section>

                    {/* Footer */}
                    <section>
                        <p className="text-sm opacity-60 mt-12 pt-8 border-t border-white/10">
                            Last updated: March 1, 2026
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
